version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://taxparser:taxparser@db:5432/tax_parser
      - REDIS_URL=redis://cache:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-2}
      - OCR_ENGINE=tesseract
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - ENABLE_DEBUG_LOGGING=false  # Set to true to enable detailed debug logging
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app  # Mount app directory for development
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - tax_parser_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=taxparser
      - POSTGRES_PASSWORD=taxparser
      - POSTGRES_DB=tax_parser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tax_parser_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxparser"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  cache:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tax_parser_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  redis_data:

networks:
  tax_parser_net:
    driver: bridge
